// HAND-AUTHORED MIGRATION: there is no .NET SDK / dotnet-ef tool available in the sandbox
// this file was authored in ("dotnet" command not found), so this could not be generated by
// running `dotnet ef migrations add InitialCreate`. It is a best-effort structural
// reproduction of what that command would produce for the model in
// src/Qistas.Infrastructure/Persistence/QistasDbContext.cs.
//
// ACTION REQUIRED before relying on this in production: on a machine with the .NET 8 SDK
// and the dotnet-ef tool installed (`dotnet tool install --global dotnet-ef`), run:
//   1. Delete this file and QistasDbContextModelSnapshot.cs (both hand-authored).
//   2. dotnet ef migrations add InitialCreate --project src/Qistas.Infrastructure --startup-project src/Qistas.Api
//   3. Inspect the generated files against this one to confirm no drift, then
//      dotnet ef database update --project src/Qistas.Infrastructure --startup-project src/Qistas.Api
//      (or simply start the API -- Program.cs calls Database.Migrate() on startup).
// At minimum, run `dotnet build` and `dotnet ef migrations has-pending-model-changes`
// against this hand-authored pair to confirm they compile and match the DbContext model
// exactly; EF Core will throw at runtime if the snapshot doesn't match OnModelCreating.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Qistas.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Outbox",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ScaleSystemReferenceId = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    Operation = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Environment = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    PayloadJson = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Attempts = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    LastError = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LastResponseJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Outbox", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "IntegrationLog",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    TimestampUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Environment = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Operation = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Success = table.Column<bool>(type: "bit", nullable: false),
                    HttpStatusCode = table.Column<int>(type: "int", nullable: true),
                    RequestJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ResponseJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Error = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DurationMs = table.Column<long>(type: "bigint", nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IntegrationLog", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Outbox_ScaleSystemReferenceId",
                table: "Outbox",
                column: "ScaleSystemReferenceId");

            migrationBuilder.CreateIndex(
                name: "IX_Outbox_Status",
                table: "Outbox",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_IntegrationLog_Operation",
                table: "IntegrationLog",
                column: "Operation");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "Outbox");

            migrationBuilder.DropTable(name: "IntegrationLog");
        }
    }
}
